spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/check_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 767678
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 100000
      # 最大连接数
      maximum-pool-size: 10
      # 自动提交
      auto-commit: true
      # 连接最大存活时间(30m)
      max-lifetime: 1800000
      # 连接超时时间(30s)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  # redis 配置
#  redis:
#    # 超时时间
#    timeout: 10000ms
#    # 服务地址
#    host: 192.168.64.137
#    # 服务端口
#    port: 5002
#    # 数据库
#    database: 1
#    lettuce:
#      pool:
#        # 最小空闲连接
#        min-idle: 5
#        # 最大连接数
#        max-active: 1024
#        # 最大连接阻塞时间
#        max-wait: 10000ms
#        # 最大空闲连接
#        max-idle: 200

# mybatis-plus配置
mybatis-plus:
  # 配置mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型别名
  type-aliases-package: com.kai.check.pojo
  # 自动驼峰命名
  configuration:
    map-underscore-to-camel-case: true

# Mybatis SQL 打印(方法接口所在的包,不是Mapper.xml所在的包)
logging:
  level:
    com.kai.server.mapper: debug

jwt:
  # jwt 存储的请求头
  tokenHeader: Authorization
  # jwt 加密解密使用的密钥
  secret: maokai
  # jwt 的超期限时间(60*60*10)
  expiration: 36000
  # jwt 负载中拿到开头
  tokenHead: Cumter


kai:
  # 指定作业存储路径
  resource: /check_resource
  # 指定结果存放的路径
  result: /check_result
  # 设置相似度检查门限参数值
  sim: 1
  # 查重结果最大值,超过返回
  resultMax: 95
  #  # 课程设计提交目录
  #  resourceDes: /check_resource_design
  #  # 课程设计查重结果目录
  #  resultDes: /check_result
  # 课程设计PDF目录
  design: /check_design
  designResource: /check_design_resource
  designResult: /chack_design_result